/**
 * This file was generated by the Jeddict
 */
package ec.renafipse.mks.modelo.cajas;

import ec.renafipse.mks.modelo.ahorros.MovimientoCuenta;
import java.io.Serializable;
import java.math.BigDecimal;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * @author willan
 */
@Entity
@Table(name = "DESGLOCE_BILLETES_ALT_DEN", schema = "MKS_CAJAS")
@XmlRootElement
public class DesgloceBilletes implements Serializable {

    private static final long serialVersionUID = 1L;
    @Id
    @GeneratedValue(generator = "GSQ_DESGLOCE_BILLETES_ALT_DEN", strategy = GenerationType.SEQUENCE)
    @SequenceGenerator(name = "GSQ_DESGLOCE_BILLETES_ALT_DEN", sequenceName = "SEQ_DESGLOCE_BILLETES_ALT_DEN", initialValue = 0, schema = "MKS_CAJAS")
    private Long codigo;

    /**
     * Codigo del movimiento
     */
    @JoinColumn(name = "CODIGO_MOVIMIENTO", referencedColumnName = "CODIGO", insertable = false, updatable = false)
    @ManyToOne(optional = false)
    private MovimientoCuenta codigoMovimiento;

    /**
     * Serie del billete
     */
    @Column(columnDefinition = "Serie del billete", unique = true, nullable = false, length = 12)
    @Basic
    private String serie;

    /**
     * Valor del billete
     */
    @Column(columnDefinition = "Valor del billete", nullable = false)
    @Basic
    private BigDecimal monto;

    public Long getCodigo() {
        return this.codigo;
    }

    public void setCodigo(Long codigo) {
        this.codigo = codigo;
    }

    public MovimientoCuenta getCodigoMovimiento() {
        return this.codigoMovimiento;
    }

    public void setCodigoMovimiento(MovimientoCuenta codigoMovimiento) {
        this.codigoMovimiento = codigoMovimiento;
    }

    public String getSerie() {
        return this.serie;
    }

    public void setSerie(String serie) {
        this.serie = serie;
    }

    public BigDecimal getMonto() {
        return this.monto;
    }

    public void setMonto(BigDecimal monto) {
        this.monto = monto;
    }

}
